services:
  database:
    image: postgres:alpine
    restart: always
    ports:
      - 6543:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - database-data:/var/lib/postgresql/data/

  kafka:
    image: bitnami/kafka
    restart: always
    ports:
      - 9095:9094
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Auto-create topics for Kafka connect / Debezium
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka-data:/bitnami/kafka

  kafka-connect:
    image: quay.io/debezium/connect
    restart: always
    ports:
      - 8083:8083
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONFIG_STORAGE_TOPIC=kafka_connect_configs
      - OFFSET_STORAGE_TOPIC=kafka_connect_offsets
      - STATUS_STORAGE_TOPIC=kafka_connect_statuses

  # Utility services

  adminer:
    image: adminer
    restart: always
    ports:
      - 10000:8080
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_DEFAULT_DB_HOST=localhost:6543
      - ADMINER_DEFAULT_DB_NAME=streaming_poc
    depends_on:
      - database

  kafka-ui:
    image: provectuslabs/kafka-ui
    restart: always
    ports:
      - 10001:8080
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=database-streaming-poc-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

  debezium-ui:
    image: debezium/debezium-ui
    restart: always
    ports:
      - 10002:8080
    environment:
      - KAFKA_CONNECT_URIS=http://kafka-connect:8083

volumes:
  database-data:
  kafka-data:
