### Get Kafka Connect status
GET http://localhost:8083/
Accept: application/json

### List Kafka Connect connectors
GET http://localhost:8083/connectors/
Accept: application/json

### Create Debezium source connector
POST http://localhost:8083/connectors
Content-Type: application/json
Accept: application/json

{
	"name": "source-connector",
	"config": {
		"connector.class": "io.debezium.connector.postgresql.PostgresConnector",
		"topic.prefix": "source-connector",
		"database.user": "admin",
		"database.dbname": "db",
		"database.hostname": "source-database",
		"database.password": "admin",
		"schema.include.list": "streaming_poc",
		"plugin.name": "pgoutput",

		"transforms": "unwrap",
		"transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
		"transforms.unwrap.fields": "op,table,lsn,source.ts_ms",
		"transforms.unwrap.add.headers": "db",
		"transforms.unwrap.delete.handling.mode": "rewrite"
	}
}

# TODO: tombstones.on.delete
# TODO: value.converter

### Create Debezium sink connector - users
POST http://localhost:8083/connectors 
Content-Type: application/json
Accept: application/json

{
    "name": "sink-connector.streaming_poc.users",
    "config": {
        "connector.class": "io.debezium.connector.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
		"connection.url": "jdbc:postgresql://sink-database/db",
		"connection.username": "admin",
		"connection.password": "admin",
		"auto.create": "true",
		"insert.mode": "upsert",
		"delete.enabled": "false",
		"primary.key.fields": "id",
		"primary.key.mode": "record_value",
		"schema.evolution": "basic",
		"use.time.zone": "UTC",
		"topics": "source-connector.streaming_poc.users",
		"table.name.format": "streaming_poc.users"
    }
}

### Create Debezium sink connector - orders
POST http://localhost:8083/connectors 
Content-Type: application/json
Accept: application/json

{
    "name": "sink-connector.streaming_poc.orders",
    "config": {
        "connector.class": "io.debezium.connector.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
		"connection.url": "jdbc:postgresql://sink-database/db",
		"connection.username": "admin",
		"connection.password": "admin",
		"auto.create": "true",
		"insert.mode": "upsert",
		"delete.enabled": "false",
		"primary.key.fields": "id",
		"primary.key.mode": "record_value",
		"schema.evolution": "basic",
		"use.time.zone": "UTC",
		"topics": "source-connector.streaming_poc.orders",
		"table.name.format": "streaming_poc.orders"
    }
}

### Create Debezium sink connector - order_items
POST http://localhost:8083/connectors 
Content-Type: application/json
Accept: application/json

{
    "name": "sink-connector.streaming_poc.order_items",
    "config": {
        "connector.class": "io.debezium.connector.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
		"connection.url": "jdbc:postgresql://sink-database/db",
		"connection.username": "admin",
		"connection.password": "admin",
		"auto.create": "true",
		"insert.mode": "upsert",
		"delete.enabled": "false",
		"primary.key.fields": "id",
		"primary.key.mode": "record_value",
		"schema.evolution": "basic",
		"use.time.zone": "UTC",
		"topics": "source-connector.streaming_poc.order_items",
		"table.name.format": "streaming_poc.order_items"
    }
}

### Get source connector status
GET http://localhost:8083/connectors/source-connector/status
Accept: application/json

### Get sink connector status
GET http://localhost:8083/connectors/sink-connector/status
Accept: application/json

### Set log level for sink connector
PUT http://localhost:8083/admin/loggers/io.debezium.connector.jdbc.JdbcSinkConnector -d '{"level": "DEBUG"}'
Content-Type:application/json
Accept: application/json

### Delete Debezium source connector
DELETE http://localhost:8083/connectors/source-connector
Accept: application/json

### Delete Debezium sink connector
DELETE http://localhost:8083/connectors/sink-connector
Accept: application/json