## Kafka Connect status

### Get Kafka Connect status
GET http://localhost:8083/
Accept: application/json

### List Kafka Connect connectors
GET http://localhost:8083/connectors/
Accept: application/json

### Get source connector status
GET http://localhost:8083/connectors/source-connector/status
Accept: application/json

### Get sink connector status - users
GET http://localhost:8083/connectors/sink-connector.streaming_poc.users/status
Accept: application/json

### Get sink connector status - orders
GET http://localhost:8083/connectors/sink-connector.streaming_poc.orders/status
Accept: application/json

### Get sink connector status - order_items
GET http://localhost:8083/connectors/sink-connector.streaming_poc.order_items/status
Accept: application/json

## Create connectors

### Create Debezium source connector
POST http://localhost:8083/connectors
Content-Type: application/json
Accept: application/json

{
	"name": "source-db-cdc-connector",
	"config": {
		"connector.class": "io.debezium.connector.postgresql.PostgresConnector",
		"topic.prefix": "source-db",
		"database.hostname": "source-database",
		"database.port": "5432",
		"database.dbname": "db",
		"database.user": "admin",
		"database.password": "admin",
		"schema.include.list": "streaming_poc",
		"plugin.name": "pgoutput",
		"snapshot.mode": "initial",
		
		"key.converter": "org.apache.kafka.connect.json.JsonConverter",
		"value.converter": "org.apache.kafka.connect.json.JsonConverter",
		"key.converter.schemas.enable": "true",
		"value.converter.schemas.enable": "true",  

		"transforms": "unwrap",
		"transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
		"transforms.unwrap.fields": "op,table,lsn,source.ts_ms",
		"transforms.unwrap.add.headers": "db",
		"transforms.unwrap.delete.handling.mode": "none",
		"transforms.unwrap.drop.tombstones": "false"
	}
}

### Create Debezium sink connector - users
POST http://localhost:8083/connectors 
Content-Type: application/json
Accept: application/json

{
    "name": "sink-connector.streaming_poc.users",
    "config": {
        "connector.class": "io.debezium.connector.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
		"connection.url": "jdbc:postgresql://sink-database/db",
		"connection.username": "admin",
		"connection.password": "admin",

		"key.converter": "org.apache.kafka.connect.json.JsonConverter",
		"value.converter": "org.apache.kafka.connect.json.JsonConverter",
		"key.converter.schemas.enable": "true",
		"value.converter.schemas.enable": "true",  

		"topics": "source-db.streaming_poc.users",
		"table.name.format": "streaming_poc.users",
		"primary.key.fields": "id",
		"primary.key.mode": "record_key",
		"auto.create": "true",
		"auto.evolve": "true",
		"schema.evolution": "basic",
		"insert.mode": "upsert",
		"delete.enabled": "false",
		"use.time.zone": "UTC"
    }
}

### Create Debezium sink connector - orders
POST http://localhost:8083/connectors 
Content-Type: application/json
Accept: application/json

{
    "name": "sink-connector.streaming_poc.orders",
    "config": {
        "connector.class": "io.debezium.connector.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
		"connection.url": "jdbc:postgresql://sink-database/db",
		"connection.username": "admin",
		"connection.password": "admin",

		"key.converter": "org.apache.kafka.connect.json.JsonConverter",
		"value.converter": "org.apache.kafka.connect.json.JsonConverter",
		"key.converter.schemas.enable": "true",
		"value.converter.schemas.enable": "true",  

		"topics": "source-db.streaming_poc.orders",
		"table.name.format": "streaming_poc.orders",
		"primary.key.fields": "id",
		"primary.key.mode": "record_key",
		"auto.create": "true",
		"auto.evolve": "true",
		"schema.evolution": "basic",
		"insert.mode": "upsert",
		"delete.enabled": "false",
		"use.time.zone": "UTC"
    }
}

### Create Debezium sink connector - order_items
POST http://localhost:8083/connectors 
Content-Type: application/json
Accept: application/json

{
    "name": "sink-connector.streaming_poc.order_items",
    "config": {
        "connector.class": "io.debezium.connector.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
		"connection.url": "jdbc:postgresql://sink-database/db",
		"connection.username": "admin",
		"connection.password": "admin",

		"key.converter": "org.apache.kafka.connect.json.JsonConverter",
		"value.converter": "org.apache.kafka.connect.json.JsonConverter",
		"key.converter.schemas.enable": "true",
		"value.converter.schemas.enable": "true",  

		"topics": "source-db.streaming_poc.order_items",
		"table.name.format": "streaming_poc.order_items",
		"primary.key.fields": "id",
		"primary.key.mode": "record_key",
		"auto.create": "true",
		"auto.evolve": "true",
		"schema.evolution": "basic",
		"insert.mode": "upsert",
		"delete.enabled": "true",
		"delete.tombstone.handling.mode": "drop",
		"use.time.zone": "UTC"
    }
}

## Delete connectors

### Delete Debezium source connector
DELETE http://localhost:8083/connectors/source-connector
Accept: application/json

### Delete Debezium sink connector - users
DELETE http://localhost:8083/connectors/sink-connector.streaming_poc.users
Accept: application/json

### Delete Debezium sink connector - orders
DELETE http://localhost:8083/connectors/sink-connector.streaming_poc.orders
Accept: application/json

### Delete Debezium sink connector - order_items
DELETE http://localhost:8083/connectors/sink-connector.streaming_poc.order_items
Accept: application/json
